### ISSUE TITLE
Select button is not working on IE11

### ISSUE THREAD

**Issue by ashishjain15880** [kzrfaisal/angular-file-uploader#48] opened 2019-03-13 11:00 UTC
I am also facing same issue. Drag and drop working for me.  Any idea?

**Comment by narindersingh07** [comment] 2019-08-01 09:34
Any luck on this. Files are not getting selected in IE11.

**Comment by kzrfaisal** [comment] 2020-11-06 06:43
Duplicate of #27

**Closed by kzrfaisal** 2020-11-06 06:43 UTC
